using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DrawDemo.WebSocket
{
    public class WordList
    {
        public static CatWord GetWord()
        {
            return WordList.GetList().OrderBy(x => Guid.NewGuid()).FirstOrDefault();
        }

        public static List<CatWord> GetList()
        {
            return new List<CatWord> { 
                new CatWord { Category = "Food", Word = "Barbecue Ribs" },
                new CatWord { Category = "Food", Word = "Caesar Salad" },
                new CatWord { Category = "Food", Word = "Cheeseburger" },
                new CatWord { Category = "Food", Word = "Chicken Fajitas" },
                new CatWord { Category = "Food", Word = "Chicken Parm" },
                new CatWord { Category = "Food", Word = "Chicken Wings" },
                new CatWord { Category = "Food", Word = "Chilli con Carne" },
                new CatWord { Category = "Food", Word = "Fettuccine Alfredo" },
                new CatWord { Category = "Food", Word = "Fish and Chips" },
                new CatWord { Category = "Food", Word = "French Toast" },
                new CatWord { Category = "Food", Word = "Hummus" },
                new CatWord { Category = "Food", Word = "Kebab" },
                new CatWord { Category = "Food", Word = "Lasagne" },
                new CatWord { Category = "Food", Word = "Peking Duck" },
                new CatWord { Category = "Food", Word = "Pierogi" },
                new CatWord { Category = "Food", Word = "Pizza" },
                new CatWord { Category = "Food", Word = "Poutine" },
                new CatWord { Category = "Food", Word = "Scotch Eggs" },
                new CatWord { Category = "Food", Word = "Sushi" },
                new CatWord { Category = "Food", Word = "Tacos" },
                new CatWord { Category = "Food", Word = "Tiramisù" },
                new CatWord { Category = "Food", Word = "Vegetable Soup" },
                new CatWord { Category = "Food", Word = "Apples" }, 
                new CatWord { Category = "Food", Word = "Apricots" }, 
                new CatWord { Category = "Food", Word = "Aubergine" }, 
                new CatWord { Category = "Food", Word = "Avocado" }, 
                new CatWord { Category = "Food", Word = "Banana" }, 
                new CatWord { Category = "Food", Word = "Berries" }, 
                new CatWord { Category = "Food", Word = "Blackberries" }, 
                new CatWord { Category = "Food", Word = "Blood oranges" }, 
                new CatWord { Category = "Food", Word = "Blueberries" }, 
                new CatWord { Category = "Food", Word = "Cantaloupe" }, 
                new CatWord { Category = "Food", Word = "Starfruit" }, 
                new CatWord { Category = "Food", Word = "Cherries" }, 
                new CatWord { Category = "Food", Word = "Corella Pear" }, 
                new CatWord { Category = "Food", Word = "Cranberry" }, 
                new CatWord { Category = "Food", Word = "Cumquat" }, 
                new CatWord { Category = "Food", Word = "Dates"}, 
                new CatWord { Category = "Food", Word = "Dragonfruit" }, 
                new CatWord { Category = "Food", Word = "Grapefruit" }, 
                new CatWord { Category = "Food", Word = "Grapes" }, 
                new CatWord { Category = "Food", Word = "Figs" }, 
                new CatWord { Category = "Food", Word = "Kiwi" }, 
                new CatWord { Category = "Food", Word = "Lemon" }, 
                new CatWord { Category = "Food", Word = "Limes" }, 
                new CatWord { Category = "Food", Word = "Lychees" }, 
                new CatWord { Category = "Food", Word = "Mango" }, 
                new CatWord { Category = "Food", Word = "Melon" }, 
                new CatWord { Category = "Food", Word = "Mandarins" }, 
                new CatWord { Category = "Food", Word = "Nectarines" }, 
                new CatWord { Category = "Food", Word = "Olives" }, 
                new CatWord { Category = "Food", Word = "Oranges" }, 
                new CatWord { Category = "Food", Word = "Passionfruit" }, 
                new CatWord { Category = "Food", Word = "Peaches" }, 
                new CatWord { Category = "Food", Word = "Pears" }, 
                new CatWord { Category = "Food", Word = "Pineapple" }, 
                new CatWord { Category = "Food", Word = "Pomegranate" }, 
                new CatWord { Category = "Food", Word = "Plums" }, 
                new CatWord { Category = "Food", Word = "Prunes" }, 
                new CatWord { Category = "Food", Word = "Snowpeas" }, 
                new CatWord { Category = "Food", Word = "Sprouts" }, 
                new CatWord { Category = "Food", Word = "Strawberries" }, 
                new CatWord { Category = "Food", Word = "Tomatoes" }, 
                new CatWord { Category = "Food", Word = "Watermelon"},
                new CatWord { Category = "Food", Word = "Artichoke" }, 
                new CatWord { Category = "Food", Word = "Asparagus" }, 
                new CatWord { Category = "Food", Word = "Bean Sprouts" }, 
                new CatWord { Category = "Food", Word = "Beans" }, 
                new CatWord { Category = "Food", Word = "Green beans" }, 
                new CatWord { Category = "Food", Word = "Broccoli" }, 
                new CatWord { Category = "Food", Word = "Brussels Sprouts" }, 
                new CatWord { Category = "Food", Word = "Cabbage" }, 
                new CatWord { Category = "Food", Word = "Capers" }, 
                new CatWord { Category = "Food", Word = "Carrot" }, 
                new CatWord { Category = "Food", Word = "Cauliflower" }, 
                new CatWord { Category = "Food", Word = "Celery" }, 
                new CatWord { Category = "Food", Word = "Chilli Pepper" }, 
                new CatWord { Category = "Food", Word = "Cucumber" }, 
                new CatWord { Category = "Food", Word = "Eggplant" }, 
                new CatWord { Category = "Food", Word = "Garlic" }, 
                new CatWord { Category = "Food", Word = "Chives" }, 
                new CatWord { Category = "Food", Word = "Green Pepper" }, 
                new CatWord { Category = "Food", Word = "Iceberg lettuce" }, 
                new CatWord { Category = "Food", Word = "Kale" }, 
                new CatWord { Category = "Food", Word = "Leeks" }, 
                new CatWord { Category = "Food", Word = "Lettuce" }, 
                new CatWord { Category = "Food", Word = "Onion" }, 
                new CatWord { Category = "Food", Word = "Okra" }, 
                new CatWord { Category = "Food", Word = "Parsnip" }, 
                new CatWord { Category = "Food", Word = "Peas" }, 
                new CatWord { Category = "Food", Word = "Peppers" }, 
                new CatWord { Category = "Food", Word = "Potatoes" }, 
                new CatWord { Category = "Food", Word = "Pumpkin" }, 
                new CatWord { Category = "Food", Word = "Radish" }, 
                new CatWord { Category = "Food", Word = "Raspberry" }, 
                new CatWord { Category = "Food", Word = "Rhubarb" }, 
                new CatWord { Category = "Food", Word = "Spinach" }, 
                new CatWord { Category = "Food", Word = "Squash" }, 
                new CatWord { Category = "Food", Word = "Sun dried tomatoes" }, 
                new CatWord { Category = "Food", Word = "Sweet Potato" }, 
                new CatWord { Category = "Food", Word = "Turnips" }, 
                new CatWord { Category = "Food", Word = "Zucchini" }, 
                new CatWord { Category = "Food", Word = "Cookie" }, 
                new CatWord { Category = "Food", Word = "Pie" }, 
                new CatWord { Category = "Food", Word = "Ice Cream" }, 
                new CatWord { Category = "Food", Word = "Pudding" }, 
                new CatWord { Category = "Food", Word = "Sweet Bread" }, 
                new CatWord { Category = "Food", Word = "Cupcake" }, 
                new CatWord { Category = "Food", Word = "Cheesecake" }, 
                new CatWord { Category = "Food", Word = "Brownie" }, 
                new CatWord { Category = "Food", Word = "Cobbler" }, 
                new CatWord { Category = "Food", Word = "Ice Cream Cake" }, 
                new CatWord { Category = "Food", Word = "Doughnut" }, 
                new CatWord { Category = "Food", Word = "Frozen Yogurt" }, 
                new CatWord { Category = "Food", Word = "Parfait" }, 
                new CatWord { Category = "Food", Word = "Sundae" }, 
                new CatWord { Category = "Food", Word = "Trifle" }, 
                new CatWord { Category = "Food", Word = "Cake Pop" }, 
                new CatWord { Category = "Food", Word = "Fruit Cake" }, 
                new CatWord { Category = "Food", Word = "Coffee Cake" }, 
                new CatWord { Category = "Food", Word = "Key Lime Pie" }, 
                new CatWord { Category = "Food", Word = "Upside Down Pineapple Cake" },
                new CatWord { Category = "Beer", Word = "Corona Extra" },
                new CatWord { Category = "Beer", Word = "Heineken" },
                new CatWord { Category = "Beer", Word = "Budweiser" },
                new CatWord { Category = "Beer", Word = "Becks" },
                new CatWord { Category = "Beer", Word = "BudLight" },
                new CatWord { Category = "Beer", Word = "Pabst Blue Ribbon" },
                new CatWord { Category = "Beer", Word = "Dos Equis" },
                new CatWord { Category = "Beer", Word = "Blue Moon" },
                new CatWord { Category = "Beer", Word = "Stella Artois" },
                new CatWord { Category = "Beer", Word = "Miller Draft" },
                new CatWord { Category = "Beer", Word = "Coors lite" },
                new CatWord { Category = "Beer", Word = "Guinness" },
                new CatWord { Category = "Beer", Word = "Kirin" },
                new CatWord { Category = "Beer", Word = "Tsingtao" },
                new CatWord { Category = "Beer", Word = "Sierra Nevada" },
                new CatWord { Category = "Beer", Word = "Rolling Rock" },
                new CatWord { Category = "Beer", Word = "Red Stripe" },
                new CatWord { Category = "Beer", Word = "Paulaner" },
                new CatWord { Category = "Beer", Word = "Patagonia" },
                new CatWord { Category = "Beer", Word = "Delirium" },
                new CatWord { Category = "Beer", Word = "Samuel Adams" },
                new CatWord { Category = "Beer", Word = "Sapporo" },
                new CatWord { Category = "Beer", Word = "Carlsberg" },
                new CatWord { Category = "Beer", Word = "Pacifico" },
                new CatWord { Category = "Beer", Word = "Quimes" },
                new CatWord { Category = "Beer", Word = "Murphys" },
                new CatWord { Category = "Beer", Word = "Birra Moretti" },
                new CatWord { Category = "Beer", Word = "Harp" },
                new CatWord { Category = "Beer", Word = "Fosters" },
                new CatWord { Category = "Beer", Word = "Hoegaarden" },
                new CatWord { Category = "Beer", Word = "Leffe" },
                new CatWord { Category = "Beer", Word = "Lowenbrau" },
                new CatWord { Category = "Animal", Word = "alligator" },
                new CatWord { Category = "Animal", Word = "crocodile" },
                new CatWord { Category = "Animal", Word = "alpaca" },
                new CatWord { Category = "Animal", Word = "ant" },
                new CatWord { Category = "Animal", Word = "antelope" },
                new CatWord { Category = "Animal", Word = "ape" },
                new CatWord { Category = "Animal", Word = "armadillo" },
                new CatWord { Category = "Animal", Word = "donkey" },
                new CatWord { Category = "Animal", Word = "baboon" },
                new CatWord { Category = "Animal", Word = "badger" },
                new CatWord { Category = "Animal", Word = "bat" },
                new CatWord { Category = "Animal", Word = "bear" },
                new CatWord { Category = "Animal", Word = "beaver" },
                new CatWord { Category = "Animal", Word = "bee" },
                new CatWord { Category = "Animal", Word = "beetle" },
                new CatWord { Category = "Animal", Word = "buffalo" },
                new CatWord { Category = "Animal", Word = "butterfly" },
                new CatWord { Category = "Animal", Word = "camel" },
                new CatWord { Category = "Animal", Word = "water buffalo" },
                new CatWord { Category = "Animal", Word = "caribou" },
                new CatWord { Category = "Animal", Word = "cat" },
                new CatWord { Category = "Animal", Word = "cattle" },
                new CatWord { Category = "Animal", Word = "cheetah" },
                new CatWord { Category = "Animal", Word = "chimpanzee" },
                new CatWord { Category = "Animal", Word = "chinchilla" },
                new CatWord { Category = "Animal", Word = "cicada" },
                new CatWord { Category = "Animal", Word = "clam" },
                new CatWord { Category = "Animal", Word = "cockroach" },
                new CatWord { Category = "Animal", Word = "cod" },
                new CatWord { Category = "Animal", Word = "coyote" },
                new CatWord { Category = "Animal", Word = "crab" },
                new CatWord { Category = "Animal", Word = "cricket" },
                new CatWord { Category = "Animal", Word = "crow" },
                new CatWord { Category = "Animal", Word = "raven" },
                new CatWord { Category = "Animal", Word = "deer" },
                new CatWord { Category = "Animal", Word = "dinosaur" },
                new CatWord { Category = "Animal", Word = "dog" },
                new CatWord { Category = "Animal", Word = "dolphin" },
                new CatWord { Category = "Animal", Word = "porpoise" },
                new CatWord { Category = "Animal", Word = "duck" },
                new CatWord { Category = "Animal", Word = "eagle" },
                new CatWord { Category = "Animal", Word = "eel" },
                new CatWord { Category = "Animal", Word = "elephant" },
                new CatWord { Category = "Animal", Word = "elk" },
                new CatWord { Category = "Animal", Word = "ferret" },
                new CatWord { Category = "Animal", Word = "fish" },
                new CatWord { Category = "Animal", Word = "fly" },
                new CatWord { Category = "Animal", Word = "fox" },
                new CatWord { Category = "Animal", Word = "frog" },
                new CatWord { Category = "Animal", Word = "toad" },
                new CatWord { Category = "Animal", Word = "gerbil" },
                new CatWord { Category = "Animal", Word = "giraffe" },
                new CatWord { Category = "Animal", Word = "gnat" },
                new CatWord { Category = "Animal", Word = "gnu" },
                new CatWord { Category = "Animal", Word = "wildebeest" },
                new CatWord { Category = "Animal", Word = "goat" },
                new CatWord { Category = "Animal", Word = "goldfish" },
                new CatWord { Category = "Animal", Word = "goose" },
                new CatWord { Category = "Animal", Word = "gorilla" },
                new CatWord { Category = "Animal", Word = "grasshopper" },
                new CatWord { Category = "Animal", Word = "guinea pig" },
                new CatWord { Category = "Animal", Word = "hamster" },
                new CatWord { Category = "Animal", Word = "hare" },
                new CatWord { Category = "Animal", Word = "hedgehog" },
                new CatWord { Category = "Animal", Word = "herring" },
                new CatWord { Category = "Animal", Word = "hippopotamus" },
                new CatWord { Category = "Animal", Word = "hornet" },
                new CatWord { Category = "Animal", Word = "horse" },
                new CatWord { Category = "Animal", Word = "hound" },
                new CatWord { Category = "Animal", Word = "hyena" },
                new CatWord { Category = "Animal", Word = "impala" },
                new CatWord { Category = "Animal", Word = "jackal" },
                new CatWord { Category = "Animal", Word = "jellyfish" },
                new CatWord { Category = "Animal", Word = "kangaroo" },
                new CatWord { Category = "Animal", Word = "wallaby" },
                new CatWord { Category = "Animal", Word = "koala" },
                new CatWord { Category = "Animal", Word = "leopard" },
                new CatWord { Category = "Animal", Word = "lion" },
                new CatWord { Category = "Animal", Word = "lizard" },
                new CatWord { Category = "Animal", Word = "llama" },
                new CatWord { Category = "Animal", Word = "locust" },
                new CatWord { Category = "Animal", Word = "louse" },
                new CatWord { Category = "Animal", Word = "macaw" },
                new CatWord { Category = "Animal", Word = "mallard" },
                new CatWord { Category = "Animal", Word = "mammoth" },
                new CatWord { Category = "Animal", Word = "manatee" },
                new CatWord { Category = "Animal", Word = "marten" },
                new CatWord { Category = "Animal", Word = "mink" },
                new CatWord { Category = "Animal", Word = "minnow" },
                new CatWord { Category = "Animal", Word = "mole" },
                new CatWord { Category = "Animal", Word = "monkey" },
                new CatWord { Category = "Animal", Word = "moose" },
                new CatWord { Category = "Animal", Word = "mosquito" },
                new CatWord { Category = "Animal", Word = "mouse" },
                new CatWord { Category = "Animal", Word = "rat" },
                new CatWord { Category = "Animal", Word = "mule" },
                new CatWord { Category = "Animal", Word = "muskrat" },
                new CatWord { Category = "Animal", Word = "otter" },
                new CatWord { Category = "Animal", Word = "ox" },
                new CatWord { Category = "Animal", Word = "oyster" },
                new CatWord { Category = "Animal", Word = "panda" },
                new CatWord { Category = "Animal", Word = "pig" },
                new CatWord { Category = "Animal", Word = "platypus" },
                new CatWord { Category = "Animal", Word = "porcupine" },
                new CatWord { Category = "Animal", Word = "prairie dog" },
                new CatWord { Category = "Animal", Word = "pug" },
                new CatWord { Category = "Animal", Word = "rabbit" },
                new CatWord { Category = "Animal", Word = "raccoon" },
                new CatWord { Category = "Animal", Word = "reindeer" },
                new CatWord { Category = "Animal", Word = "rhinoceros" },
                new CatWord { Category = "Animal", Word = "salmon" },
                new CatWord { Category = "Animal", Word = "sardine" },
                new CatWord { Category = "Animal", Word = "scorpion" },
                new CatWord { Category = "Animal", Word = "seal" },
                new CatWord { Category = "Animal", Word = "sea lion" },
                new CatWord { Category = "Animal", Word = "serval" },
                new CatWord { Category = "Animal", Word = "shark" },
                new CatWord { Category = "Animal", Word = "sheep" },
                new CatWord { Category = "Animal", Word = "skunk" },
                new CatWord { Category = "Animal", Word = "snail" },
                new CatWord { Category = "Animal", Word = "snake" },
                new CatWord { Category = "Animal", Word = "spider" },
                new CatWord { Category = "Animal", Word = "squirrel" },
                new CatWord { Category = "Animal", Word = "swan" },
                new CatWord { Category = "Animal", Word = "termite" },
                new CatWord { Category = "Animal", Word = "tiger" },
                new CatWord { Category = "Animal", Word = "trout" },
                new CatWord { Category = "Animal", Word = "turtle " },
                new CatWord { Category = "Animal", Word = "tortoise" },
                new CatWord { Category = "Animal", Word = "walrus" },
                new CatWord { Category = "Animal", Word = "wasp" },
                new CatWord { Category = "Animal", Word = "weasel" },
                new CatWord { Category = "Animal", Word = "whale" },
                new CatWord { Category = "Animal", Word = "wolf" },
                new CatWord { Category = "Animal", Word = "wombat" },
                new CatWord { Category = "Animal", Word = "woodchuck" },
                new CatWord { Category = "Animal", Word = "worm" },
                new CatWord { Category = "Animal", Word = "yak" },
                new CatWord { Category = "Animal", Word = "yellowjacket" },
                new CatWord { Category = "Animal", Word = "zebra" }
            };
        }
    }

    public class CatWord
    {
        public string Category { get; set; }
        public string Word { get; set; }
    }
}
